version: "3.8"

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres

  adminer:
    image: adminer
    ports:
      - 9000:8080

volumes:
  postgres:
