version: "3.8"

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres

  adminer:
    image: adminer
    ports:
      - 9000:8080

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      # - RABBITMQ_DEFAULT_VHOST="/"
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres:
