version: "3.8"

services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    networks:
      - spring
    volumes:
      - postgres:/data/postgres

  adminer:
    image: adminer
    networks:
      - spring
    ports:
      - 9000:8080

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      # - RABBITMQ_DEFAULT_VHOST="/"
    networks:
      - spring
    ports:
      - "5672:5672"
      - "15672:15672"

  # eureka-server:
  #   image: arilson/eureka-server:latest
  #   container_name: eureka-server
  #   ports:
  #     - "8761:8761"
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=docker
  #   networks:
  #     - spring
  #   depends_on:
  #     - zipkin
  # apigw:
  #   image: arilson/apigw:latest
  #   container_name: apigw
  #   ports:
  #     - "8083:8083"
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=docker
  #   networks:
  #     - spring
  #   depends_on:
  #     - zipkin
  #     - eureka-server
  customer:
    image: arilson/customer:latest
    container_name: customer
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - zipkin
      - postgres
      - rabbitmq
  fraud:
    image: arilson/fraud:latest
    container_name: fraud
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - zipkin
      - postgres
      - rabbitmq
  notification:
    image: arilson/notification:latest
    container_name: notification
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - zipkin
      - postgres
      - rabbitmq

networks:
  spring:
    driver: bridge

volumes:
  postgres:
