server:
  port: 8083

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
    correlation: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  #  endpoints.web.exposure.include: '*'
  tracing:
    sampling.probability: 1.0
    propagation.type: w3c
    enabled: true
    baggage.enabled: true
  #  metrics:
  #    distribution.percentiles-histogram.http.server.requests: true
  zipkin.tracing.endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}
