spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
    correlation: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  #  endpoints.web.exposure.include: '*'
  tracing:
    sampling.probability: 1.0
    propagation.type: w3c
    enabled: true
    baggage.enabled: true
  #  metrics:
  #    distribution.percentiles-histogram.http.server.requests: true
  zipkin.tracing.endpoint: ${ZIPKIN_ENDPOINT:http://zipkin:9411/api/v2/spans}
